### PR TITLE
twitter example enhancements

### PR DESCRIPTION
**Pull request by alrocar**
Updated the notebook to use the last version of `tweepy` and used a separate [module](https://github.com/tinybirdco/tinybird-python-sdk) that wraps all the sink stuff which looks complicated.

Also added a `requirements.txt` file since the `tinybird-python-sdk` needs to be installed from git (we could publish to pypi indeed...)

If we'd like to simplify the code much more, like having a one-pager we could minimize the things we do `on_data(raw_tweet)` and just have something like:

```python
def on_data(self, raw_tweet):
        if (time.monotonic() - self.start_time) > self.limit:
            print('Finished time period')
            self.disconnect()
            return False
        tweet = json.loads(raw_tweet)
        if 'created_at' not in tweet or 'id' not in tweet or 'text' not in tweet:
          return
        date = str(tweet['created_at'])
        text = tweet['text']
        tw = {
          "search_label": self.search_label,
          "tweet": text,
          "date": parsedate_to_datetime(date).strftime("%Y-%m-%d %H:%M:%S")
        }
        self.datasource << tweet
```

up to you!

HTH, let me know what do you think.

### CODE REVIEW

**Comment by AlisonDavey** [comment]
Thanks a million. Much cleaner. Good to be using a more recent `tweepy`.

Are we happy to encourage people to use the `tinybird-python-sdk` instead of the API?

I'm happy to have the longer `on_data`.

Running in Google Colab I no longer see the streamed messages (they go to the terminal). 🤔

**Comment by alrocar** [comment]
> Are we happy to encourage people to use the tinybird-python-sdk instead of the API?

We could change:

`self.datasource << tweet` by a `requests.post` call to the `events` endpoint if that's clearer.

I'm OK with the `tinybird-python-sdk` but I don't have a strong opinion, leaving to you the final decision.

> Running in Google Colab I no longer see the streamed messages (they go to the terminal). 🤔

mmm... could you try removing these two lines?

```
import logging
logging.getLogger().setLevel(logging.WARNING)
```

The SDK should print the messages, but only with logging.INFO level I guess, maybe that's the issue.

**Comment by alrocar** [comment]
> Are we happy to encourage people to use the tinybird-python-sdk instead of the API?

We could change:

`self.datasource << tweet` by a `requests.post` call to the `events` endpoint if that's clearer.

I'm OK with the `tinybird-python-sdk` but I don't have a strong opinion, leaving to you the final decision.

> Running in Google Colab I no longer see the streamed messages (they go to the terminal). 🤔

mmm... could you try removing these two lines?

```
import logging
logging.getLogger().setLevel(logging.WARNING)
```

The SDK should print the messages, but only with logging.INFO level I guess, maybe that's the issue.

**Comment by alrocar** [comment]
> Are we happy to encourage people to use the tinybird-python-sdk instead of the API?

We could change:

`self.datasource << tweet` by a `requests.post` call to the `events` endpoint if that's clearer.

I'm OK with the `tinybird-python-sdk` but I don't have a strong opinion, leaving to you the final decision.

> Running in Google Colab I no longer see the streamed messages (they go to the terminal). 🤔

mmm... could you try removing these two lines?

```
import logging
logging.getLogger().setLevel(logging.WARNING)
```

The SDK should print the messages, but only with logging.INFO level I guess, maybe that's the issue.

**Comment by alrocar** [comment]
> Are we happy to encourage people to use the tinybird-python-sdk instead of the API?

We could change:

`self.datasource << tweet` by a `requests.post` call to the `events` endpoint if that's clearer.

I'm OK with the `tinybird-python-sdk` but I don't have a strong opinion, leaving to you the final decision.

> Running in Google Colab I no longer see the streamed messages (they go to the terminal). 🤔

mmm... could you try removing these two lines?

```
import logging
logging.getLogger().setLevel(logging.WARNING)
```

The SDK should print the messages, but only with logging.INFO level I guess, maybe that's the issue.

**Comment by alrocar** [comment]
(sorry if you got multiple notifications, there was a glitch in github and my comment was published several times)

**Pull request merged**
